## Clock Signal
set_property PACKAGE_PIN W5 [get_ports CCLK]
set_property IOSTANDARD LVCMOS33 [get_ports CCLK]
create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports CCLK]

## Switches
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property PACKAGE_PIN V17 [get_ports reset]

## 7 segment display = Anode Selects
set_property IOSTANDARD LVCMOS33 [get_ports {anode_select[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode_select[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode_select[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode_select[0]}]
set_property PACKAGE_PIN U2 [get_ports {anode_select[0]}]
set_property PACKAGE_PIN U4 [get_ports {anode_select[1]}]
set_property PACKAGE_PIN V4 [get_ports {anode_select[2]}]
set_property PACKAGE_PIN W4 [get_ports {anode_select[3]}]

## 7 segment display - Cathode pins
set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[0]}]
set_property PACKAGE_PIN W7 [get_ports {LED_out[6]}]
set_property PACKAGE_PIN W6 [get_ports {LED_out[5]}]
set_property PACKAGE_PIN U8 [get_ports {LED_out[4]}]
set_property PACKAGE_PIN V8 [get_ports {LED_out[3]}]
set_property PACKAGE_PIN U5 [get_ports {LED_out[2]}]
set_property PACKAGE_PIN V5 [get_ports {LED_out[1]}]
set_property PACKAGE_PIN U7 [get_ports {LED_out[0]}]

## Count to LEDs in binary
set_property IOSTANDARD LVCMOS33 [get_ports {count[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {count[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {count[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {count[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {count[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {count[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {count[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {count[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {count[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {count[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {count[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {count[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {count[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {count[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {count[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {count[0]}]
set_property PACKAGE_PIN U16 [get_ports {count[0]}]
set_property PACKAGE_PIN E19 [get_ports {count[1]}]
set_property PACKAGE_PIN U19 [get_ports {count[2]}]
set_property PACKAGE_PIN V19 [get_ports {count[3]}]
set_property PACKAGE_PIN W18 [get_ports {count[4]}]
set_property PACKAGE_PIN U15 [get_ports {count[5]}]
set_property PACKAGE_PIN U14 [get_ports {count[6]}]
set_property PACKAGE_PIN V14 [get_ports {count[7]}]
set_property PACKAGE_PIN V13 [get_ports {count[8]}]
set_property PACKAGE_PIN V3 [get_ports {count[9]}]
set_property PACKAGE_PIN W3 [get_ports {count[10]}]
set_property PACKAGE_PIN U3 [get_ports {count[11]}]
set_property PACKAGE_PIN P3 [get_ports {count[12]}]
set_property PACKAGE_PIN N3 [get_ports {count[13]}]
set_property PACKAGE_PIN P1 [get_ports {count[14]}]
set_property PACKAGE_PIN L1 [get_ports {count[15]}]
